[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

# Proxy /api/* to the function path (cleaner URLs for clients)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
