name: build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Build
        env:
          NODE_ENV: production
        run: npm run build
      - name: Upload build artifact (dist)
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: dist