name: build and deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          NODE_ENV: production
        run: npm run build

      - name: Upload build artifact (dist)
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: dist
  deploy_production:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: web-build
          path: dist

      - name: Deploy Production to Netlify
        run: |
          npx --yes netlify-cli deploy \
            --auth "${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            --site "${{ secrets.NETLIFY_SITE_ID }}" \
            --dir dist \
            --prod \
            --message "GitHub Actions deploy ${GITHUB_SHA::7}" \
            --json > ./DeployOutput.json
      - name: Upload deploy output
        uses: actions/upload-artifact@v4
        with:
          name: deploy-output
          path: DeployOutput.json
  lighthouse:
    needs: deploy_production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: deploy-output
          path: ./
      - name: Set unique deploy target url
        id: setuniquedeploytarget
        run: |
          UNIQUE_DEPLOY_TARGET=$(jq -r '.deploy_url' ./DeployOutput.json)

          echo "unique_deploy_target=$UNIQUE_DEPLOY_TARGET" >> $GITHUB_OUTPUT
      - name: audit urls using lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ steps.setuniquedeploytarget.outputs.unique_deploy_target }}
          uploadartifacts: true # save results as an action artifacts
          configPath: ./lighthouserc.json
      - name: move reports to dist
        run:
          find target -type f -name '*.json' ! -name 'manifest.json' -exec cp {} dist/ \;
      - name: Upload build artifact with report
        uses: actions/upload-artifact@v4
        with:
          name: web-build-with-reports
          path: dist


