name: build and deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          NODE_ENV: production
        run: npm run build

      - name: Upload build artifact (dist)
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: dist
  deploy_production:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: web-build
          path: dist

      - name: Deploy Production to Netlify
        run: |
          npx --yes netlify-cli deploy \
            --auth "${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            --site "${{ secrets.NETLIFY_SITE_ID }}" \
            --dir dist \
            --message "GitHub Actions deploy ${GITHUB_SHA::7}" \
            --json > ./DeployOutput.json
      - name: Upload deploy output
        uses: actions/upload-artifact@v4
        with:
          name: deploy-output
          path: DeployOutput.json
  lighthouse:
    needs: deploy_production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: deploy-output
          path: ./
      - name: Set unique deploy target url
        id: setuniquedeploytarget
        run: |
          UNIQUE_DEPLOY_TARGET=$(jq -r '.deploy_url' ./DeployOutput.json)

          echo "unique_deploy_target=$UNIQUE_DEPLOY_TARGET" >> $GITHUB_OUTPUT
      - name: audit urls using lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ steps.setuniquedeploytarget.outputs.unique_deploy_target }}
          uploadartifacts: true # save results as an action artifacts
          configPath: ./lighthouserc.json
      - uses: actions/download-artifact@v4
        with:
          name: lighthouse-results
          path: ./lhci-reports
      - name: upload outputs to blob storage
        env:
          NETLIFY_AUTH_TOKEN: "${{ secrets.NETLIFY_AUTH_TOKEN }}"
          NETLIFY_SITE_ID: "${{ secrets.NETLIFY_SITE_ID }}"
        run: |
          npm install -g netlify-cli

          timestamp=$(date +%Y-%m-%d-%H-%M-%S)
          for file in ./lhci-reports/lhr*; do
              if [[ -f "$file" ]]; then
                  filename=$(basename "$file")
                  netlify blobs:set lighthouse-reports "${timestamp}_${filename}"  --input  "$file"
                  echo "Uploaded: ${timestamp}_${filename}"
              fi
          done